import Foundation

/// Pre-defined seed data for debug environments.
///
/// **Responsibilities:**
/// - Providing a diverse set of journal entries for testing search and filtering.
/// - Ensuring coverage of various tag types (Futures, Tickers, Topics).
public enum DebugSeedData {
    public static let messages: [String] = [
        // MARK: - Asset Only (25)
        "Watching /ES for a bounce at 4500.",
        "Long $AAPL on the dip.",
        "Shorting /NQ against vwap.",
        "$TSLA looking weak at the open.",
        "/GC rejecting the daily high.",
        "Accumulating $NVDA for a swing.",
        "/CL inventory numbers were bearish.",
        "$AMD relative strength is impressive.",
        "Scalping /YM in the chop.",
        "$MSFT holding the 200 SMA.",
        "/SI volume is drying up.",
        "Quick trade on $GOOGL.",
        "/ES retesting the breakdown level.",
        "$AMZN earnings play looks risky.",
        "/NQ melting up into the close.",
        "$META filling the gap.",
        "/CL bouncing off support.",
        "$NFLX breaking out of the wedge.",
        "/GC flagging on the 15m.",
        "$SPY rejecting 400.",
        "/SI weird price action today.",
        "$QQQ leading the market down.",
        "/YM finding buyers at the lows.",
        "$IWM rotation is evident.",
        "/ES chopping around in a range.",

        // MARK: - Topic Only (25)
        "Felt huge #fomo seeing that move go without me.",
        "Good #discipline today, sat on hands.",
        "Revenge trading caused this #tilt.",
        "Perfect #setup on the 5 minute chart.",
        "Waiting for a clean #breakout.",
        "Caught the #reversal perfectly.",
        "Need more #patience in the morning.",
        "Poor #execution on the exit.",
        "Weekend #review time.",
        " battling #fomo all morning.",
        "Major #tilt after that slip.",
        "Sticking to the #setup rules.",
        "False #breakout trapped me.",
        "Looking for a #reversal pattern.",
        "My #patience paid off.",
        "Sloppy #execution cost me 5 ticks.",
        "Mid-week #review.",
        "Avoided #fomo today.",
        "Controlled the #tilt.",
        "A+ #setup presented itself.",
        "Volume confirmed the #breakout.",
        "Missed the #reversal.",
        "Testing my #patience.",
        "Focused on #execution.",
        "End of day #review.",

        // MARK: - Asset + Topic (25)
        "/ES choppy, causing some #tilt.",
        "$AAPL #setup looks prime for tomorrow.",
        "Chased /NQ, definitely #fomo.",
        "$TSLA #breakout failed.",
        "Waiting for /GC #reversal.",
        "$NVDA trade required huge #patience.",
        "Bad #execution on /CL short.",
        "$AMD #review shows I exited too early.",
        "/YM #setup was valid, just stopped out.",
        "$MSFT moving, trying to avoid #fomo.",
        "/SI grinding, testing my #discipline.",
        "$GOOGL #breakout with volume.",
        "Caught the /ES #reversal at the low.",
        "$AMZN trade was pure #tilt.",
        "/NQ #execution was perfect.",
        "$META #setup forming on the hourly.",
        "/CL #fomo got the best of me.",
        "$NFLX #breakout seems legit.",
        "/GC #reversal confirmed.",
        "$SPY chopped me up, #tilt city.",
        "/SI #patience is key here.",
        "$QQQ #execution needs work.",
        "/YM #review of the morning session.",
        "$IWM #setup on the daily.",
        "/ES #breakout above yesterday's high.",

        // MARK: - Mixed / Plain (25)
        "Market is extremely quiet today.",
        "Watching the spread between $SPY and $QQQ.",
        "Rotation from tech into energy sectors.",
        "Just a boring day.",
        "/ES and /NQ moving in opposite directions.",
        "Earnings season is causing volatility.",
        "Need to clear my head.",
        "Big news dropping at 2pm.",
        "Lunch break.",
        "Closing up shop early.",
        "$AAPL and $MSFT holding the index up.",
        "/CL and /GC both rallying.",
        "Fed meeting minutes released.",
        "Volume is surprisingly low.",
        "Gap up and sit.",
        "$NVDA vs $AMD relative strength.",
        "Keeping an eye on the VIX.",
        "Sold half, holding the rest.",
        "Flat for the day.",
        "Market breadth is improving.",
        "/ES testing the overnight low.",
        "$TSLA looks heavy.",
        "Nice rally into the close.",
        "Pre-market prep done.",
        "Done for the week."
    ]
}
